/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/office.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['01_office001_1']: THREE.Mesh
    ['01_office001_2']: THREE.Mesh
    ['01_office001_3']: THREE.Mesh
    ['01_office001_4']: THREE.Mesh
    ['01_office001_5']: THREE.Mesh
    ['01_office001_6']: THREE.Mesh
    ['01_office001_7']: THREE.Mesh
    ['01_office001_8']: THREE.Mesh
    ['01_office001_9']: THREE.Mesh
    ['01_office001_10']: THREE.Mesh
    ['01_office001_11']: THREE.Mesh
    ['01_office002']: THREE.Mesh
    ['01_office002_1']: THREE.Mesh
    ['01_office002_2']: THREE.Mesh
    ['01_office002_3']: THREE.Mesh
    ['01_office002_4']: THREE.Mesh
    ['01_office002_5']: THREE.Mesh
  }
  materials: {
    Wall: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    PastelPinkTexture: THREE.MeshStandardMaterial
    PasteBlueTexture: THREE.MeshStandardMaterial
    Wood1: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    Wood2: THREE.MeshStandardMaterial
    ['WoodQuarteredChiffon001_6K.002']: THREE.MeshStandardMaterial
    ['PasteBlueTexture.002']: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    ['WoodQuarteredChiffon001_6K.001']: THREE.MeshStandardMaterial
    ['PastelPinkTexture.001']: THREE.MeshStandardMaterial
    ['Wood2.1']: THREE.MeshStandardMaterial
  }
  animations: any
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/office.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, -2.019, 1.255]}>
        <mesh geometry={nodes['01_office001_1'].geometry} material={materials.Wall} />
        <mesh geometry={nodes['01_office001_2'].geometry} material={materials['Material.001']} />
        <mesh geometry={nodes['01_office001_3'].geometry} material={materials.PastelPinkTexture} />
        <mesh geometry={nodes['01_office001_4'].geometry} material={materials.PasteBlueTexture} />
        <mesh geometry={nodes['01_office001_5'].geometry} material={materials.Wood1} />
        <mesh geometry={nodes['01_office001_6'].geometry} material={materials['Material.002']} />
        <mesh geometry={nodes['01_office001_7'].geometry} material={materials.Material} />
        <mesh geometry={nodes['01_office001_8'].geometry} material={materials['Material.003']} />
        <mesh geometry={nodes['01_office001_9'].geometry} material={materials['Material.005']} />
        <mesh geometry={nodes['01_office001_10'].geometry} material={materials['Material.007']} />
        <mesh geometry={nodes['01_office001_11'].geometry} material={materials.Wood2} />
      </group>
      <group position={[0, 0.284, -0.937]}>
        <mesh geometry={nodes['01_office002'].geometry} material={materials['WoodQuarteredChiffon001_6K.002']} />
        <mesh geometry={nodes['01_office002_1'].geometry} material={materials['PasteBlueTexture.002']} />
        <mesh geometry={nodes['01_office002_2'].geometry} material={materials.Mirror} />
        <mesh geometry={nodes['01_office002_3'].geometry} material={materials['WoodQuarteredChiffon001_6K.001']} />
        <mesh geometry={nodes['01_office002_4'].geometry} material={materials['PastelPinkTexture.001']} />
        <mesh geometry={nodes['01_office002_5'].geometry} material={materials['Wood2.1']} />
      </group>
    </group>
  )
}

useGLTF.preload('/office.glb')
