/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/sewingmachine1.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cube001: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder006: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cube002: THREE.Mesh
    Cylinder012: THREE.Mesh
    Cylinder013_1: THREE.Mesh
    Cylinder013_2: THREE.Mesh
    Cylinder014_1: THREE.Mesh
    Cylinder014_2: THREE.Mesh
    pivot: THREE.Mesh
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane003_2: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
  }
  animations: any
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const SewingMachineModel = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('./models/sewingmachine1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[-0.174, 0.453, -0.906]} rotation={[Math.PI / 2, 0, 0]} scale={[0.536, 0.045, 0.536]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.002']} position={[-0.135, -0.701, -0.875]} rotation={[Math.PI / 2, 0, 0]} scale={[0.339, 0.051, 0.339]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} position={[-0.097, -1.293, -0.93]} rotation={[Math.PI / 2, 0, 0]} scale={[0.084, 0.007, 0.084]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.002']} position={[-0.308, -1.293, -0.906]} rotation={[Math.PI / 2, 0, 0]} scale={[0.084, 0.007, 0.084]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.002']} position={[0.141, -1.293, -0.906]} rotation={[Math.PI / 2, 0, 0]} scale={[0.084, 0.007, 0.084]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-5.897, -2.479, -0.024]} scale={[0.436, 0.147, 0.376]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-5.932, -0.625, 0]} scale={[0.053, 1.01, 0.053]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.002']} position={[-3.301, 2.647, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.497, 0.174, 0.497]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.002']} position={[-6.312, 0.58, -0.911]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.084, 0.056, 0.084]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.002']} position={[-6.312, 0.79, -0.946]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.084, 0.056, 0.084]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.002']} position={[-6.312, 0.341, -0.866]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.084, 0.056, 0.084]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.002']} position={[-0.554, 2.838, 0]} scale={[0.055, 0.708, 0.055]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.002']} position={[-0.255, 2.838, 0]} scale={[0.055, 0.463, 0.055]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[-4.144, -3.799, 0.358]} rotation={[-Math.PI, 0, 0]} scale={[-8.919, -0.54, -5.345]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.002']} position={[1.468, 1.676, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.135, 1]} />
      <group position={[1.021, -2.804, -1.862]} scale={[0.333, 0.534, 0.333]}>
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder013_2.geometry} material={materials['Material.004']} />
      </group>
      <group position={[1.021, -2.975, -2.846]} rotation={[0.45, -0.6, -1.274]} scale={[0.333, 0.534, 0.333]}>
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.pivot.geometry} material={materials['Material.005']} position={[-0.768, -3.192, -2.309]} rotation={[0, 1.169, -Math.PI]} scale={[0.365, 0.251, 0.365]}>
        <group position={[-0.1, -0.047, -0.763]} scale={[1, 1.453, 1]}>
          <mesh geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.007']} />
        </group>
        <group position={[0.046, 0.047, -0.763]} rotation={[0, 0.051, Math.PI]} scale={[1, 1.453, 1]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.007']} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/sewingmachine1.glb')

export default SewingMachineModel;